Repository mr-sh202/Metro-Train-Distance-Time-Calculator, pull requests merged in 2021-10, with the labels that each got.

#12 Set Form properties and Data Bindings.
  Feedback-server.py
  Task.py
Labels: help wanted, good first issue, hacktoberfest-accepted

#13 Automatic Feedback Mail Server side code
  Automatic-Mail.py
Labels: hacktoberfest-accepted

#14 Create snakeGame.py
  snakeGame.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#15 add tkinter buttons
  Tkinter butons.py
Labels: hacktoberfest-accepted, hacktoberfest

#16 created a functional calculator using python
  calculator.py
Labels: hacktoberfest-accepted, hacktoberfest

#17 Create login interface using python
  login.py
Labels: hacktoberfest-accepted, hacktoberfest

#19 created user information page which handles the data of the user usin…
  user information.py
Labels: hacktoberfest-accepted, hacktoberfest

#20 checking the distance between 2 stations provided by the user using p…
  distance information.py
Labels: hacktoberfest-accepted, hacktoberfest
